config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'
  get 'users/index'
  get 'persons/profile'
  get 'about' => 'pages#about', as: "about"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'posts#index', as: "home"
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  get 'persons/profile', as: 'user_root'
  resources :users, only: [:show, :index]
  delete "users/:id", to: "users#destroy"
  resources :posts, only: [:show, :index] do
    resources :comments
  end
  resources :contacts
  namespace :admin do
    resources :posts, except: [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
  has_many :comments
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected
  def check_admin
    redirect_to home_path, notice:"Access Denied!" unless current_user.admin?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params # params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    posts_path
  end
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.all
  end
  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(post_params)
      redirect_to contact_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to home_path
  end

  def edit
    @contact  = Contact.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @contact = Contact.new(post_params)
    if @contact.save
      redirect_to home_path
    else
      render 'new'
    end
  end

  private def post_params # params
    params.require(:contact).permit(:name,:email, :subject,:message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'About us'
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find_by_id(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to home_path, notice: 'User deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/edit.html.erb
<br>
<h1>Edit post</h1>
<%= form_for [:admin,@post] do |f| %>
 <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %> 
      <div class="alert alert-danger"> <%= msg %></div>
  <% end %>       
 <% end %>      
<p>
  Name<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
  <p>
  Text<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
   <p>
  <%= f.submit({:class => 'btn btn-success'}) %>
   </p>
<% end %>

app/views/admin/posts/new.html.erb
<br>
<h1>Create a new post</h1>
<%= form_for [:admin,@post] do |f| %>
 <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %> 
      <div class = "alert alert-danger"> <%= msg %></div>
  <% end %>
 <% end %>      
<p>
  Name<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
  <p>
  Text<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
    <%#= f.rich_text_area(:body, {:class => 'form-control'}) %>
</p>
   <p>
  <%= f.submit({:class => 'btn btn-success'}) %>
   </p>
<% end %>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
<br>
<h1>Messages from users</h1>
<% @contact.each do |contact| %>
  <div class="col-4 col-6-medium col-12-small">
    <article class="box style2">
      <p> Name: <%= contact.name %></p>
      <p>Email: <%= contact.email%></p>
      <p>Subject: <%= contact.subject %></p>
      <p>Message: <%= contact.message %></p>
      <%= button_to "Delete", contact_path(contact),  method: :delete, :class => 'btn btn-danger' %>
    </article>
    <hr>
  </div>
<% end %>
  <% else %>
    <% controller.redirect_to home_path %>
  <% end %>
<% else %>
<% controller.redirect_to home_path %>

<% end %>

app/views/persons/profile.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <br>
    <h1 align="center">AdminArea</h1>
    <article class="box style2">
      <h3>Admin Email is  <i><%= current_user.email%></i></h3>
      <h3>Admin NickName is  <i><%= current_user.username%></i></h3>
      <li><%= link_to "ViewUsers", users_path, :class => 'btn btn-dark'%></li>
      <br>
      <li><%= link_to "ViewUsersMessages", contacts_path, :class => 'btn btn-dark'%></li>
      <br>
      <li><%= link_to "Edit", edit_user_registration_path, :class => 'btn btn-dark'%></li>
      <br>
      <li><%= link_to "Create Post", new_admin_post_path, :class => 'btn btn-dark'%></li>
    </article>
  <% else %>
    <br>
    <h1 align="center">Profile</h1>
    <article class="box style2">
      <h3>Your Email is  <i><%= current_user.email%></i></h3>
      <h3>Your NickName is  <i><%= current_user.username%></i></h3>
      <li><%= link_to "Edit", edit_user_registration_path, :class => 'btn btn-dark'%></li>

    </article>
  <% end %>
<% else %>
  <% controller.redirect_to home_path %>
<% end %>

app/views/posts/edit.html.erb
<br>
<h1>Редактировать пост</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
 <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %> 
      <div class="alert alert-danger"> <%= msg %></div>
  <% end %>       
 <% end %>      
<p>
  Название<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
  <p>
  Текст поста<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
   <p>
  <%= f.submit({:class => 'btn btn-success'}) %>
   </p>
<% end %>

app/views/posts/index.html.erb
<!-- Home -->
<article id="top" class="wrapper style1">
  <div class="container">
    <div class="row">
      <div class="col-4 col-5-large col-12-medium">
        <span class="image fit"><%= image_tag("pic00.jpg", :alt => "") %></span>
      </div>
      <div class="col-8 col-7-large col-12-medium">
        <header>
          <h1>Welcome! This is </h1>
          <h1> <strong>Coding Blogs</strong></h1>
        </header>
        <p>A web-site for programmers from over the world</p>
        <a href="#portfolio" class="button large scrolly">Learn about what I do</a>
      </div>
    </div>
  </div>
</article>



<!-- Portfolio -->
<article id="portfolio" class="wrapper style3">
  <div class="container">
    <header>
      <h2>Here’s some posts I made recently.</h2>
      <p>Recently added</p>
    </header>
    <div class="row">

        <% @post.each do |post| %>
        <div class="col-4 col-6-medium col-12-small">
          <article class="box style2">
            <%= link_to image_tag("codecode.jpg", :alt => ""), post_path(post), :class => 'image featured' %>
            <%= link_to post.title, post_path(post), :class => 'btn btn-outline-primary' %>
            <p><%= post.body[0..150] %></p>
          </article>
        </div>
        <% end %>
    </div>
    <footer>
      <p>Get a free registration</p>
      <%= link_to  "Create a new account",new_user_registration_path, :class => 'button large scrolly'%>
    </footer>
  </div>
</article>

app/views/posts/new.html.erb
<br>
<h1>Добавить новый пост</h1>
<%= form_for :post, url: posts_path do |f| %>
 <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %> 
      <div class = "alert alert-danger"> <%= msg %></div>
  <% end %>       
 <% end %>      
<p>
  Название<br>
   <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
  <p>
  Текст поста<br>
   <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
   <p>
  <%= f.submit({:class => 'btn btn-success'}) %>
   </p>
<% end %>

app/views/posts/show.html.erb
<br>
<h1 class="text-center" xmlns="http://www.w3.org/1999/html"><%= @post.title %></h1>

<p><%=@post.body %></p>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <hr>
    <%= link_to "Edit", edit_admin_post_path(@post),data: {
      turbo_confirm: "Are you sure?"
    }, :class => 'btn btn-warning' %>
    <%= button_to "Delete", admin_post_path(@post),  method: :delete, :class => 'btn btn-danger' %>
    <hr>
  <% end %>
<% end %>
<%= form_for ([@post, @post.comments.build])  do |f| %>
  <div class="col-md-16">
    <p>
      <% if user_signed_in? %>
      <hr>
      <h2>Add a comment</h2>
      <%= f.hidden_field :username, :value =>current_user.username, :class => 'form-control' %></div>
      <p>
        Text<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
      </p>
      <p>
        <%= f.submit("Add", { :class => 'btn btn-warning'}) %>
      </p>
    <% else %>
        <%= f.hidden_field :username, :value =>"Guest", :class => 'form-control' %></div>
    <% end %>
    </p>
<% end %>
<hr>
<h2>All comments</h2>
<br>
<% @post.comments.each do |comment| %>
  <% if comment.username %>
  <div class = "alert alert-light">
    <div> <strong> <%= comment.username %>: </strong> <%=comment.body %></div>
    <hr>
  </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
<br>
<h1>User List</h1>
<% @users.each do |u| %>
  Email: <%= u.email %><br/>
      <%= link_to u.email, user_path(u), :class => 'btn btn-outline-primary' %>
      <%= button_to "Delete", user_path(u),  method: :delete, :class => 'btn btn-danger' %>
      <hr>
<% end %>
  <% else %>
    <% controller.redirect_to home_path %>
  <% end %>
<% else %>
  <% controller.redirect_to home_path %>
<% end %>

app/views/users/show.html.erb
<br>
<h1 align="center">Profile</h1>
<article class="box style2">
  <h3>Email is  <i><%= @user.email%></i></h3>
</article>