config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'
  get 'users/index'
  get 'persons/profile'
  get 'about' => 'pages#about', as: "about"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'posts#index', as: "home"
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  get 'persons/profile', as: 'user_root'
  resources :users, only: [:show, :index]
  delete "users/:id", to: "users#destroy"
  resources :posts, only: [:show, :index] do
    resources :comments
  end
  resources :contacts
  namespace :admin do
    resources :posts, except: [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
  has_many :comments
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected
  def check_admin
    redirect_to home_path, notice:"Access Denied!" unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    posts_path
  end
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.all
  end
  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(post_params)
      redirect_to contact_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to home_path
  end

  def edit
    @contact  = Contact.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @contact = Contact.new(post_params)
    if @contact.save
      redirect_to home_path
    else
      render 'new'
    end
  end

  private def post_params # params
    params.require(:contact).permit(:name,:email, :subject,:message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'About us'
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find_by_id(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to home_path, notice: 'User deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      
   <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>
  <nav id="nav">
    <ul class="container">
      <li><span class="nav-link px-2 link-secondary"><%= link_to "HomePage", home_path%></span></li>

      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li><span class="nav-link px-2 link-secondary"><%= link_to "Admin", user_root_path%></span></li>
          <li><span class="nav-link px-2 link-secondary"><%= link_to "Create Post", new_admin_post_path%></span></li>
        <% else %>
          <li><span class="nav-link px-2 link-secondary"><%= link_to "Profile", user_root_path%></span></li>
        <% end %>
        <li><span class="nav-link px-2 link-secondary"><%= link_to "Log out", destroy_session_path(:user), :method => :delete %></span></li>
      <% else %>
        <li><span class="nav-link px-2 link-secondary"><%= link_to "Log In", new_user_session_path%></span></li>
      <% end %>

      <li><span class="nav-link px-2 link-secondary"><%= link_to "About Us", about_path%></span></li>
    </ul>
  </nav>




  </header>
  </div>
  <div class ="container">
  <body>
    <%= yield %>
  </body>
  </div>
  <footer>
    <!-- Contact -->
    <article id="contact" class="wrapper style4">
      <div class="container medium">
        <header>
          <h2>Have me make stuff for you.</h2>
          <p>Just do it</p>
        </header>
        <div class="row">
          <div class="col-12">
            <%= form_for Contact.new do |f| %>
              <div class="row">
                <div class="col-6 col-12-small">
                  Name<br>
                  <%= f.text_field(:name) %>
                </div>
                <div class="col-6 col-12-small">
                  Email<br>
                  <%= f.text_field(:email) %>
                </div>
                <div class="col-12">
                  Subject<br>
                  <%= f.text_field(:subject) %>
                </div>
                <div class="col-12">
                  Message<br>
                  <%= f.text_field(:message) %>
                </div>
                <div class="col-12">
                  <ul class="actions">
                    <%= f.submit "Send Message" %>
                    <li><input type="reset" value="Clear Form" class="alt" /></li>
                  </ul>
                </div>
              </div>
            <% end %>
          </div>
          <div class="col-12">
            <hr />
            <h3>Find me on ...</h3>
            <ul class="social">
              <li><a href="https://github.com/Kalsash" class="icon brands fa-github"><span class="label" >Github</span></a></li>
            </ul>
            <hr />
          </div>
        </div>
        <footer>
          <ul id="copyright">
            <li>&copy; Coding Blogs</li><li>Git: <a href="https://github.com/Kalsash/CodingBlogs">repository</a></li>
          </ul>
        </footer>
      </div>
    </article>
  </footer>
</html>

app/views/pages/about.html.erb
<br>
<h1 class="text-center"><%=@heading %></h1>
<p class="text-center">
  A web application for programmers who want to share their knowledge with others.
</p>
<span class="image fit"><%= image_tag("rails.jpg", :alt => "") %></span>